version: "3.9"

services:

  api:
   build: .
   ports:
     - 3000:3000
   container_name: mern-api
   restart: always
   depends_on:
    - db
    - cache
    - pgadmin

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_USER=amin
      - POSTGRES_PASSWORD=amin
    ports:
      - '5431:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
  
    container_name: pgadmin-db
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"


  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    container_name: redis-cache
    command: [ "redis-server" ]
    volumes: 
      - redis-data:/data


volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local