module.exports = {
  ADD_USER: "ADD_USER",
  GET_USERS: "GET_USERS",
  SEND_MESSAGE: "SEND_MESSAGE",
  GET_MESSAGE: "GET_MESSAGE",
  IS_TYPING: "IS_TYPING",
  STOP_TYPING: "STOP_TYPING",
  GET_TYPING: "GET_TYPING",
};
